import type { Metadata } from "next";
import { Pixelify_Sans, Inconsolata} from "next/font/google";

import "./globals.css";

export const pixel = Pixelify_Sans({ subsets: ["latin"], weight: ["400", "500","600", "700"] });
export const sans = Inconsolata({ subsets: ["latin"], weight: ["200", "300", "400", "500","600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-primary"
      >
        {children}
      </body>
    </html>
  );
}
